/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Platform_Types.h"


// register addresses

#define RCC_BASE	0x40021000
#define PORTA_BASE	0x40010800

#define RCC_APB2ENR	*(vint32_t*)(RCC_BASE + 0x18)
#define RCC_CFGR	*(vint32_t*)(RCC_BASE + 0x04)
#define GPIOA_CRH	*(vint32_t*)(PORTA_BASE + 0x04)
#define GPIOA_ODR	*(vint32_t*)(PORTA_BASE + 0x0C)

typedef union{
	vint32_t all_fields;
	struct{
		vint32_t reserved:13;
		vint32_t pin13	 :1;
		vint32_t pin14	 :1;
		vint32_t pin15	 :1;
	}ODR_field;
}R_ODR_t;

volatile R_ODR_t *R_ODR = (volatile R_ODR_t *)(PORTA_BASE + 0x0C);

int main(void)
{
	/*Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	Set and cleared by software to control the division factor of the APB high-speed clock
	(PCLK2).
	0xx: HCLK not divided
	100: HCLK divided by 2
	101: HCLK divided by 4
	110: HCLK divided by 8
	111: HCLK divided by 16*/
	RCC_CFGR |= (0b101 << 11);

	/*Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	Set and cleared by software to control the division factor of the APB low-speed clock
	(PCLK1).
	Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
	0xx: HCLK not divided
	100: HCLK divided by 2
	101: HCLK divided by 4
	110: HCLK divided by 8
	111: HCLK divided by 16*/
	RCC_CFGR |= (0b100 << 8);

	RCC_APB2ENR |= (1<<2); // Enable RCC Clock
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1){
		R_ODR->ODR_field.pin13 = 1;
		for(int i=0; i<100000;i++);
		R_ODR->ODR_field.pin13 = 0;
		for(int i=0; i<100000;i++);
	}
	return 0;
}
