/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Platform_Types.h"



// register addresses

#define RCC_BASE	0x40021000
#define PORTB_BASE	0x40010C00

#define RCC_APB2ENR	*(vint32_t*)(RCC_BASE + 0x18)
#define GPIOB_CRL	*(vint32_t*)(PORTB_BASE)
#define GPIOB_CRH	*(vint32_t*)(PORTB_BASE + 0x04)
#define GPIOB_ODR	*(vint32_t*)(PORTB_BASE + 0x0C)

typedef union{
	vint32_t all_fields;
	struct{
		vint32_t pin0	 :1;
		vint32_t pin1	 :1;
		vint32_t pin2	 :1;
		vint32_t pin3	 :1;
		vint32_t pin4	 :1;
		vint32_t pin5	 :1;
		vint32_t pin6	 :1;
		vint32_t pin7	 :1;
		vint32_t pin8	 :1;
		vint32_t pin9	 :1;
		vint32_t pin10   :1;
		vint32_t pin11	 :1;
		vint32_t pin12	 :1;
		vint32_t pin13	 :1;
		vint32_t pin14	 :1;
		vint32_t pin15	 :1;
	}ODR_field;
}R_ODR_t;

volatile R_ODR_t *R_ODR = (volatile R_ODR_t *)(PORTB_BASE + 0x0C);
uint8 g_variables[3] = {1,2,3};
uint8 const const_variables[3] = {1,2,3};
uint8 BSS_VAR[3];
int main(void)
{
	RCC_APB2ENR |= (1<<3); // Enable RCC Clock for port B
	GPIOB_CRL = (1<<1);
	while(1){
		R_ODR->ODR_field.pin0 = 1;
		for(int i=0; i<5000;i++);
		R_ODR->ODR_field.pin0 = 0;
		for(int i=0; i<5000;i++);
	}
	return 0;
}
